### ISSUE TITLE
Config & mod idea's Enhancements

### ISSUE THREAD

**Issue by Kylebartaous** [sekwah41/SekC-Physics#22]
-In-game config, config that works w/ fabric mod menu
-Add option to toggle the mod, on & off w/ in game, It gets a bit laggy then killing off a bunch of mobs at the same time in a mob grinder, & rendering that rage-doll for them
-Support for shaders ( not sure if all ready a thing)
-In / out of game config to be able to edit part of the mod, ie stuff like, how many rag-dolls can be renders at once on the screen, how fast until, a rag-doll despawns ( could help a bit w/ lag), if the mod is on, or off atm, ect ..

**Comment by sekwah41** [comment]
Sorry for no response I did end up leaving modding for a while for uni.

Shaders seem supported, configs are supported out of game at least (though I wasn't really looking at that for fabric as its got a lot of its own handlers)

Sadly due to changes in priorities, I am planning to drop fabric support for now. Though depending on how much time I have or if I want to experiment I may try to port some versions over.

As these parts are focused for in fabric I will be closing this for now though I will take a look at adding them into forge at least.
